name: compile

on:
  pull_request:
  push:

jobs:
  compile:
    name: Compile Server & Studio
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Grep .Net version
        run: |
          dotnet_version=$(grep '<TargetFramework>' < src/Raven.Server/Raven.Server.csproj | tr -cd [:digit:].)
          echo "DOTNET_VERSION=${dotnet_version}.x" >> $GITHUB_ENV
      - name: Install 3.1 sdk
        if: startsWith( env.DOTNET_VERSION, '3' )
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 3.1.x
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.0'
      - name: Restore
        run: |
          git clean -xfd
          dotnet restore

      - name: Build Server
        run: |
          dotnet build

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Restore
        run: |
          npm install
          npm run restore
        working-directory: src/Raven.Studio

      - name: Compile Studio
        run: |
          npm run compile
        working-directory: src/Raven.Studio

