name: tests/fast

on:
  push:
    branches:
        - v5.1

  pull_request:
    branches:
        - v5.1
jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
        matrix:
          os: [ ubuntu-latest, windows-latest ]
        fail-fast: false  
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.100-rc.1.20452.10

    - name: Install dependencies
      run: dotnet restore

    - name: Test - Release
      run: dotnet test --configuration Release --no-restore
      env: # Or as an environment variable
        RAVEN_LICENSE: ${{ secrets.RAVEN_LICENSE }}
        RAVEN_MAX_RUNNING_TESTS: 1
      working-directory: ./test/FastTests
